# Publishes the SDK to GitHub Repo after a successful build and test
# for more info see: https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-java-packages-with-gradle

name: Android SDK Publish
on:
  release:
    types: [ created ]
jobs:
  publish:
    name: Publish SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Assemble & Test
        run: gradle build --stacktrace
      - name: Publish to GitHub Packages
        run: gradle publish --stacktrace
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
